# Generated by Django 3.2.3 on 2021-05-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_career_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career_post',
            name='from_year',
            field=models.DateField(),
        ),
    ]
