# Generated by Django 3.2.3 on 2021-05-20 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_career_post_from_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='career_post',
            name='to_year',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
