# Generated by Django 3.2.3 on 2021-05-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_career_post_to_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='landingpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='static/LandingPageStuff')),
                ('quote', models.TextField()),
                ('intro', models.TextField()),
                ('resume', models.FileField(upload_to='static/LandingPageStuff')),
                ('social_links', models.URLField()),
                ('skills', models.TextField(max_length=400)),
            ],
        ),
    ]
