# Generated by Django 3.2.3 on 2021-05-21 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_landingpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='social_links',
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('LandingPage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialSites', to='blog.landingpage')),
            ],
        ),
    ]
