# Generated by Django 3.2.3 on 2021-05-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210521_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='social_json',
            field=models.JSONField(null=True),
        ),
    ]
