# Generated by Django 3.2.3 on 2021-05-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210521_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='project/images')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('features', models.TextField()),
                ('tech_used', models.TextField()),
            ],
        ),
    ]
